### ISSUE TITLE
Module works connecting on 2.4.2 but not the newest 3.0

### ISSUE THREAD

**Issue by sweetapollo** [bitfocus/companion-module-aja-helo#14]
Module fails to connect to AJA Helo on 3.0 Device is running 4.3.0.8-12r with Classic model. I can switch between older version of companion and it will work but on newer it states OK for a few seconds and then state "Connection Failure
Failed to connect to device"

Logs show the following when I stop the connection and remake it. But it still states the above error

23.06.06 17:37:29 Instance/Controller: Disable instance Helo_Recorder
23.06.06 17:37:29 Instance/ModuleHost: Connection "Helo_Recorder" stopped
23.06.06 17:37:35 Instance/Controller: Enable instance Helo_Recorder
23.06.06 17:37:35 Instance/ModuleHost: Starting connection: "Helo_Recorder"(yvIy9p5SvbRIcLJGUqP04)
23.06.06 17:37:35 Instance/ModuleHost: Connection "Helo_Recorder" started
23.06.06 17:37:35 Instance/ModuleHost: Registered module client "yvIy9p5SvbRIcLJGUqP04"
23.06.06 17:37:35 Instance/Controller: instance "Helo_Recorder" configuration updated
23.06.06 17:37:37 Instance/Controller: instance "Helo_Recorder" configuration updated

**Comment by Caleb-Wishart** [comment]
I'll try and investigate this issue this weekend.

I can get it to work fine in my demo program but will test with hardware.

**Comment by Caleb-Wishart** [comment]
I've just done some additional testing, it seems running the same code on my local machine has a different result to the package that is shipped, I'll look into this further

**Comment by mpiller1221** [comment]
Any luck on getting this working correctly with 3.0?

**Comment by Caleb-Wishart** [comment]
My running theory is that the node-fetch module isn't playing nicely and have been working on switching over to the built in fetch but unfortunately haven't had the chance to test on hardware yet as I have been busy.

**Comment by Caleb-Wishart** [comment]
I've updated the code to remove the node-fetch dependency and requested that the updated version be added to companion. 

Did some additional testing to make sure it works when packaged. 🤞

**Comment by mpiller1221** [comment]
Thank you so much Caleb! Such a help. Hoping that Bitfocus will get the update pushed out soon. Appreciate all your work.

**Comment by Caleb-Wishart** [comment]
Confirmed working in latest beta 3.1.0+6064
