### ISSUE TITLE
New Feature(s)

### ISSUE THREAD

**Issue by tim-barr** [bitfocus/companion-module-aja-helo#2]
This is a great plug-in.
Would it be possible to add the following new features?
1) Set Config/Audio Source - (ex: would allow "muting/unmuting audio")
2) Set Config/Audio Input Level
3) Set Config/Video Source 
4) An alternative to granular "config" controls would be to allow loading a Particular Preset
5) Feedback feature to show current Recording and Streaming statuses
6) Feedback/variable to show percentage of free storage

Thanks!

(Note: If I posted this question int he wrong place - my apologies.  I am new to Companion.

**Comment by canerdianeh** [comment]
Definitely agree with the need for record/stream feedback into companion. Would also like to see the profile selector show them by name rather than by number.

**Comment by canerdianeh** [comment]
I don't believe input selection can be done via the HELO API, however.

**Comment by thumperdisney** [comment]
+1 for this request, feedback for status of record and stream being the most important and access to call presets would allow for input changes. not perfect but better than nothing.

**Comment by tim-barr** [comment]
Thanks thumperdisney for the bump.

**Comment by Caleb-Wishart** [comment]
Record / stream feedback is now done.
Not sure if any of the other requests are still relevant, can take a look if given a ping.

**Comment by tim-barr** [comment]
Thanks Caleb-Wishart.  the feedback will definitely be helpful!
If any of the others are easy, that would be great too.

**Comment by Caleb-Wishart** [comment]
@tim-barr, I've implemented 1,2,3 on my branch (see above commits) but unsure about what you mean with 4.
> 4. An alternative to granular "config" controls would be to allow loading a Particular Preset

Would you be able to elaborate?

Additionally, there are certain limitations with the API: 
> 2. Set Config/Audio Input Level

Only works for Analog input and in increments of 6dB.

If there are other implementations available on the API that you are interested in then let me know
(See `http://{host}/descriptors.html`)

> Would also like to see the profile selector show them by name rather than by number.

I'll look into this later

**Comment by Caleb-Wishart** [comment]
> If there are other implementations available on the API that you are interested in then let me know
> (See http://{host}/descriptors.html)

I'll continue to try and support any requests for this module in the future.
If you are looking for something in particular just open an issue and notify me.
