### ISSUE TITLE
Feature Request - Custom Variables in File Names

### ISSUE THREAD

**Issue by JayHWilliams** [bitfocus/companion-module-aja-helo#5]
Would it be possible to include the ability to use custom variables in the rename file function?

**Comment by josephdadams** [comment]
@Caleb-Wishart can you add this? :)

Here's a parsing of custom vars example where if the user has entered a custom variable into the field, it will parse that value and use it: https://github.com/bitfocus/companion-module-bmd-hyperdeck/blob/c0c01f7fe9deed224841189142ae2eede959d8a4/index.js#L778

**Comment by Caleb-Wishart** [comment]
@josephdadams Yes I can take a look.

In truth I already started but couldn't find an example of how to get the variable referencing.
I'll take a look at the link thanks.

I've found there isn't too much documentation on variables and need to look at other modules / the source code for reference.

**Comment by Caleb-Wishart** [comment]
Implemented in https://github.com/Caleb-Wishart/companion-module-aja-helo/commit/3768b4884a17c42c053b95cd5f20f772d78cadeb. Will be in next merge.
